[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"code" = { path = "../code/" }
rustyline = "9.1.0"
log = "0.4.14"
